// Vercel build for the RTVIO Studio web UI (see vercel.json at the repo root
// and rtvio/docs/REMOTE_ACCESS.md). Copies the Studio's own web folder - the
// same files the Studio serves locally - into dist/, laid out the way
// index.html references them (/static/...), and writes static/config.js
// pointing the page at the processing PC's public URL.
//
//   RTVIO_API_URL=https://studio.example.com node deploy/vercel/build.mjs
import { cpSync, rmSync, writeFileSync } from "node:fs";

const api = String(process.env.RTVIO_API_URL || "").trim().replace(/\/+$/, "");
if (!/^https:\/\/[^/\s]+$/.test(api)) {
  console.error(
    "RTVIO_API_URL must be set to the processing PC's public https origin, e.g. " +
      "https://studio.example.com (Vercel: Project Settings -> Environment Variables). Got: " +
      JSON.stringify(api),
  );
  process.exit(1);
}

const web = new URL("../../rtvio/src/rtvio/studio/web/", import.meta.url);
const dist = new URL("./dist/", import.meta.url);

rmSync(dist, { recursive: true, force: true });
cpSync(web, new URL("static/", dist), { recursive: true });
cpSync(new URL("index.html", web), new URL("index.html", dist));
writeFileSync(
  new URL("static/config.js", dist),
  `/* generated by deploy/vercel/build.mjs */\nwindow.RTVIO_API_URL = ${JSON.stringify(api)};\n`,
);
console.log(`RTVIO Studio UI built into deploy/vercel/dist -> API ${api}`);
